### PR TITLE
upgrade to nova-4

### LINKED ISSUE #79: Anyone working on a Nova 4 upgrade?
Seeing some errors and not displaying correctly.

### PR DESCRIPTION
**Pull request by Grafikart**
I did most of the work to upgrade to Nova 4 but you may need to add some style cause the classnames changed

Here is the render for my Nova 4.1 dashboard

image

laravel-nova is removed and it uses the dependency from composer : https://nova.laravel.com/docs/4.0/upgrade.html#removal-of-laravel-nova-npm-dependency

Fix #79

### CODE REVIEW

**Comment by ctessier** [comment]
Hi @Grafikart 

Thank you for your work!

I guess these changes will make the package incompatible with Nova prior to version 4? If so, I guess we will have to merge that to a new branch for a 2.x.

Also, I couldn't find any upgrade guide for package maintainers. Did you find any?

Clément

**Comment by Grafikart** [comment]
Hi, 

You guessed right, this break compatibility with previous version of nova so it need to be a major number upgrade.
For the upgrade I followed [the guide](https://nova.laravel.com/docs/4.0/upgrade.html) offered on nova but there is nothing related to package except (this part](https://nova.laravel.com/docs/4.0/upgrade.html#removal-of-laravel-nova-npm-dependency 

> Custom Nova packages that are developed outside of a nova-components directory should declare laravel/nova as a "dev" Composer dependency, and then define a laravel-nova Mix alias that points to the packages.js file within your custom package's vendor directory

**Comment by mziraki** [comment]
@ctessier hi, any update about this PR?

**Comment by SupchickCode** [comment]
i think many people wait for it.
Thanks u a lot =)

**Comment by ctessier** [comment]
Hi everyone 👋

First, I wanted to thank you all very much for the interest you are showing for this package 🙏

Unfortunately, as one needs to get a new license to upgrade to Nova's latest version ([*v4 Silver Surfer*](https://nova.laravel.com/releases/4.0.0)), I cannot help complete this PR and work on the compatibility with Nova 4 before I get a new license.

To help me purchase one, I created a [GitHub sponsor page](https://github.com/sponsors/ctessier) to allow people wanting to support my work to make a donation.

So if the *Advanced Image Field* helps your business, or if you simply wish to contribute, I will appreciate any donations.

Thank you very much for your support!
I'm looking forward to keep maintaining this package 💪

Clément

**Comment by hspromo** [comment]
Mate, can you please just accept the pull request? Can even make it a separate tag or branch. Need to add this to my composer. Its been a month. Getting frustrating you won't accept this guys work just because you don't have a license anymore.

**Comment by hspromo** [comment]
And I emailed nova on your behalf. They should not charge developers like you who built plugins for Nova. Ridiculous.

**Comment by ctessier** [comment]
> Mate, can you please just accept the pull request? Can even make it a separate tag or branch. Need to add this to my composer. Its been a month. Getting frustrating you won't accept this guys work just because you don't have a license anymore.

Thank you for your message @hspromo. 
I understand your frustration, however, I decided not to merge this PR yet for the very simple reason that I have no way to test it out and contribute to the branch.

Since people start to get impatient, I am willing to merge it now to the branch `2.x` so you guys can update your composer with the dev branch if you want to, while we are still working on the support for Nova 4. 

However, this would mean using an unstable version and you have to understand that I won't be able guarantee the well working of the package on this branch. So any reported issue would be voided and you would need to contribute if you find anything that need fixing.

Regards

**Pull request merged**
