### PR TITLE
Added new method for intervention WebP support

### LINKED ISSUE #106: Webp
Hello! As the webp format is getting more and more popular, it'd be great to add this format to your beautiful plugin.
Additionally, I'd like to have an opportunity to store the original file as well. It's very useful in a regular CMS.

### PR DESCRIPTION
**Pull request by Ruitjes**
Hi @ctessier 

Hope you can find the time to check my PR and hopefully approve it. 

I hope I've implemented it the right way, if not please let me know so I can change it accordingly. Tested it locally worked as intended.

Its currently only limited to use `webp` and not for all the other possibly encodings [see.](https://image.intervention.io/v2/api/encode)

Fixes #106.

### CODE REVIEW

**Comment by ctessier** [comment]
Hi @Ruitjes 

Thank you for your contribution!

If the need is to be able to convert the output image to WebP, it could totally be another format as well.
Therefore, I would rather make a more generic method (`convert` for instance) to save the image in a given format.

What do you think?
We could do something like below, where the output format would also be used as the file extension is specified.

```php
AdvancedImage::make('Photo')->convert('webp'); 

public function convert($format) 
{
    $this->outputFormat = $format;

    return $this;
}

if ($this->outputFormat) {
    $this->image->encode($this->outputFormat);
}
```

See https://image.intervention.io/v2/api/encode for the available formats.

**Comment by Ruitjes** [comment]
Thanks for your quick response @ctessier!

I totally agree with your comment, thus I have made the needed changes to support all the encoding formats by Intervention.  Please have a look again :).

**Comment by Ruitjes** [comment]
@ctessier Don't want to come across as impatient, but I was wondering if you could review my pull request sometime :)

**Review by ctessier — APPROVED** [review]

**Comment by ctessier** [comment]
Hi @Ruitjes 

I am merging after a few adjustments.
I am on holidays so I am doing my best to do some final testing and publish a new release.

Thank you so much for your contribution!

**Pull request merged**
